version: "2.4"
services:
  go-mock:
    image: ${IMG_NAME}
    container_name: ${NAME}_${VERSION}
    ports:
      - ${PORT}:8081
    volumes:
      - ${RESOURCES_DIR}:/usr/local/app/resources
      - ${LOG_DIR}:/usr/local/app/log
    restart: always
    networks:
      - go-mock-network
    logging:
      driver: json-file
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILES}"
    command: ./zerver_lin.exe
    mem_limit: ${CONTAINER_MAX_MEMORY}
    memswap_limit: ${CONTAINER_MAX_SWAP_MEMORY}

networks:
  go-mock-network:
